# Generated by Django 5.2.3 on 2025-09-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('news', 'News'), ('predictions', 'Predictions'), ('results', 'Results'), ('analysis', 'Analysis'), ('general', 'General'), ('rewind', 'Rewind'), ('player_ratings', 'Player Ratings'), ('team_ratings', 'Team Ratings'), ('league_ratings', 'League Ratings'), ('drop_zone', 'Drop Zone')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/'),
        ),
    ]
