# Generated by Django 5.2.3 on 2025-09-05 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cloudinary_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
