# Generated by Django 5.2.3 on 2025-07-28 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='goals_diffrerence',
        ),
    ]
