# Generated by Django 5.2.3 on 2025-07-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_remove_teams_goals_diffrerence'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='goals_difference',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teams',
            name='power',
            field=models.FloatField(default=0.0),
        ),
    ]
