# Generated by Django 5.2.3 on 2025-08-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0003_teams_goals_difference_teams_points_teams_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
