# Generated by Django 5.2.3 on 2025-08-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0004_league_slug'),
    ]

    operations = [
    ]
